# src/main/resources/application.yml
#server:
#  port: 8080

#flask:
#  api:
#    base-url: http://192.168.1.52:5000  # Your Raspberry Pi's IP and Flask port		
#spring:
#  datasource:
#   url: jdbc:h2:file:./data/authdb
#   driver-class-name: org.h2.Driver
#   username: sa
#   password: password
#  jpa:
#   hibernate:        
#    ddl-auto: update
#   show-sql: true

# Optional: enable H2 console at /h2-console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

# JWT config
#jwt:
#   secret: "thisIsASecureJWTSecretKeyThatIsAtLeast32Chars"
#   expirationMs: 86400000  # 1 day

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics
#  endpoint:
#    health:
#      show-details: always
#    metrics:
#      enabled: true
